//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Localization {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class CliOptions {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CliOptions() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("Localization.CliOptions", typeof(CliOptions).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static string VerbCreate {
            get {
                return ResourceManager.GetString("VerbCreate", resourceCulture);
            }
        }
        
        public static string VerbConfig {
            get {
                return ResourceManager.GetString("VerbConfig", resourceCulture);
            }
        }
        
        public static string CreateUser {
            get {
                return ResourceManager.GetString("CreateUser", resourceCulture);
            }
        }
        
        public static string CreateComments {
            get {
                return ResourceManager.GetString("CreateComments", resourceCulture);
            }
        }
        
        public static string ConfigScheduleMonthly {
            get {
                return ResourceManager.GetString("ConfigScheduleMonthly", resourceCulture);
            }
        }
        
        public static string ConfigScheduleWeekly {
            get {
                return ResourceManager.GetString("ConfigScheduleWeekly", resourceCulture);
            }
        }
        
        public static string ConfigScheduleDaily {
            get {
                return ResourceManager.GetString("ConfigScheduleDaily", resourceCulture);
            }
        }
        
        public static string ConfigScheduleHourly {
            get {
                return ResourceManager.GetString("ConfigScheduleHourly", resourceCulture);
            }
        }
        
        public static string ConfigSnapshotDevice {
            get {
                return ResourceManager.GetString("ConfigSnapshotDevice", resourceCulture);
            }
        }
        
        public static string VerbList {
            get {
                return ResourceManager.GetString("VerbList", resourceCulture);
            }
        }
        
        public static string VerbRestore {
            get {
                return ResourceManager.GetString("VerbRestore", resourceCulture);
            }
        }
        
        public static string RestoreSnapshot {
            get {
                return ResourceManager.GetString("RestoreSnapshot", resourceCulture);
            }
        }
        
        public static string DeleteSnapshot {
            get {
                return ResourceManager.GetString("DeleteSnapshot", resourceCulture);
            }
        }
        
        public static string DeleteAll {
            get {
                return ResourceManager.GetString("DeleteAll", resourceCulture);
            }
        }
        
        public static string VerbDelete {
            get {
                return ResourceManager.GetString("VerbDelete", resourceCulture);
            }
        }
        
        public static string VerbListDevices {
            get {
                return ResourceManager.GetString("VerbListDevices", resourceCulture);
            }
        }
    }
}
