//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Localization {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Phrases {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Phrases() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("Localization.Phrases", typeof(Phrases).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static string MountedDevices {
            get {
                return ResourceManager.GetString("MountedDevices", resourceCulture);
            }
        }
        
        public static string Device {
            get {
                return ResourceManager.GetString("Device", resourceCulture);
            }
        }
        
        public static string Size {
            get {
                return ResourceManager.GetString("Size", resourceCulture);
            }
        }
        
        public static string MountPoint {
            get {
                return ResourceManager.GetString("MountPoint", resourceCulture);
            }
        }
        
        public static string Type {
            get {
                return ResourceManager.GetString("Type", resourceCulture);
            }
        }
        
        public static string Label {
            get {
                return ResourceManager.GetString("Label", resourceCulture);
            }
        }
        
        public static string SnapshotInterrupted {
            get {
                return ResourceManager.GetString("SnapshotInterrupted", resourceCulture);
            }
        }
        
        public static string DeletingIncompleteSnapshot {
            get {
                return ResourceManager.GetString("DeletingIncompleteSnapshot", resourceCulture);
            }
        }
        
        public static string NeedToDeleteLastSnapshot {
            get {
                return ResourceManager.GetString("NeedToDeleteLastSnapshot", resourceCulture);
            }
        }
        
        public static string Elapsed {
            get {
                return ResourceManager.GetString("Elapsed", resourceCulture);
            }
        }
        
        public static string Completed {
            get {
                return ResourceManager.GetString("Completed", resourceCulture);
            }
        }
        
        public static string TimeRemaining {
            get {
                return ResourceManager.GetString("TimeRemaining", resourceCulture);
            }
        }
        
        public static string UserSnapshots {
            get {
                return ResourceManager.GetString("UserSnapshots", resourceCulture);
            }
        }
        
        public static string SnapshotName {
            get {
                return ResourceManager.GetString("SnapshotName", resourceCulture);
            }
        }
        
        public static string SnapshotComments {
            get {
                return ResourceManager.GetString("SnapshotComments", resourceCulture);
            }
        }
        
        public static string SnapshotDeleting {
            get {
                return ResourceManager.GetString("SnapshotDeleting", resourceCulture);
            }
        }
        
        public static string SnapshotDeletingAll {
            get {
                return ResourceManager.GetString("SnapshotDeletingAll", resourceCulture);
            }
        }
        
        public static string ConfigSaved {
            get {
                return ResourceManager.GetString("ConfigSaved", resourceCulture);
            }
        }
        
        public static string SnapshotCreating {
            get {
                return ResourceManager.GetString("SnapshotCreating", resourceCulture);
            }
        }
        
        public static string DateTimeLocal {
            get {
                return ResourceManager.GetString("DateTimeLocal", resourceCulture);
            }
        }
        
        public static string SnapshotRestoring {
            get {
                return ResourceManager.GetString("SnapshotRestoring", resourceCulture);
            }
        }
    }
}
